    package FormUI.TrangChu;

import FormDAO.DSDKDao;
import FormDAO.DoanhThuDao;
import FormDAO.DungCuDao;
import FormDAO.HocVienDao;
import FormDAO.KhoaTapDao;
import FormDAO.LichTapDao;
import FormDAO.NhanVienDao;
import FormDAO.TaiKhoanDao;
import FormOOB.DSDK;
import FormOOB.DoanhThu;
import FormOOB.DungCu;
import FormOOB.HocVien;
import FormOOB.KhoaTap;
import FormOOB.LichTap;
import FormOOB.NhanVien;
import FormOOB.TaiKhoan;
import FormUI.Login.Login;
import SPClass.DoiMatKhauHelper;
import java.awt.Color;
    import java.awt.Dimension;
    import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author DELL
 */
public class TrangChuHocVien extends javax.swing.JFrame {
    String user = "ThanhNP";
    public TrangChuHocVien() {
        initComponents();
        //ThongKeNhanh();
        LoiKhuyen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoiMatKhau = new javax.swing.JDialog();
        jPanel21 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtXacNhan = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btXacNhan = new javax.swing.JButton();
        TimKiemKhoaTap = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        pnKT1 = new javax.swing.JScrollPane();
        pnkt_tkkt = new javax.swing.JPanel();
        KhoaTapDaDangKy = new javax.swing.JDialog();
        jPanel15 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        pnKT2 = new javax.swing.JScrollPane();
        pnkt_ktddk = new javax.swing.JPanel();
        LichTap = new javax.swing.JDialog();
        jPanel16 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        pnKT4 = new javax.swing.JScrollPane();
        pnkt_lt = new javax.swing.JPanel();
        CaNhan = new javax.swing.JDialog();
        jPanel19 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtHoTen_CN = new javax.swing.JLabel();
        txtID_CN = new javax.swing.JLabel();
        txtNgayDK_CN = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtDienThoai_CN = new javax.swing.JLabel();
        JOptionPane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btQLTaiKhoan = new javax.swing.JButton();
        btQLNhanVien = new javax.swing.JButton();
        btQLKhoaTap = new javax.swing.JButton();
        btCaNhan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        btDoiMatKhau = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        btDangXuat = new javax.swing.JButton();
        mainFrame = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtslKhoaTapDaDangKy = new javax.swing.JLabel();
        txtslKhoaTapDangThucHien = new javax.swing.JLabel();
        txtslKhoaTapDaHuy = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtChieuCao = new javax.swing.JTextField();
        txtCanNang = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtKetQua = new javax.swing.JLabel();
        txtNhanXet = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtLoiKhuyen = new javax.swing.JLabel();

        DoiMatKhau.setModal(true);
        DoiMatKhau.setResizable(false);
        DoiMatKhau.setSize(new java.awt.Dimension(405, 251));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Đổi mật khẩu");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mật khẩu mới");

        txtMatKhauMoi.setBackground(new java.awt.Color(255, 255, 255));
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        txtXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        txtXacNhan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Xác nhận");

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setForeground(new java.awt.Color(153, 153, 255));

        btXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btXacNhan.setText("Xác nhận");
        btXacNhan.setContentAreaFilled(false);
        btXacNhan.setFocusPainted(false);
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel22))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DoiMatKhauLayout = new javax.swing.GroupLayout(DoiMatKhau.getContentPane());
        DoiMatKhau.getContentPane().setLayout(DoiMatKhauLayout);
        DoiMatKhauLayout.setHorizontalGroup(
            DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DoiMatKhauLayout.setVerticalGroup(
            DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TimKiemKhoaTap.setModal(true);
        TimKiemKhoaTap.setResizable(false);
        TimKiemKhoaTap.setSize(new java.awt.Dimension(645, 475));
        TimKiemKhoaTap.setType(java.awt.Window.Type.UTILITY);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setBackground(new java.awt.Color(0, 204, 51));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Danh sách khoá tập có sẵn");

        pnKT1.setBackground(new java.awt.Color(246, 233, 220));
        pnKT1.setBorder(null);

        pnkt_tkkt.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout pnkt_tkktLayout = new javax.swing.GroupLayout(pnkt_tkkt);
        pnkt_tkkt.setLayout(pnkt_tkktLayout);
        pnkt_tkktLayout.setHorizontalGroup(
            pnkt_tkktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        pnkt_tkktLayout.setVerticalGroup(
            pnkt_tkktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        pnKT1.setViewportView(pnkt_tkkt);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnKT1)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnKT1))
        );

        javax.swing.GroupLayout TimKiemKhoaTapLayout = new javax.swing.GroupLayout(TimKiemKhoaTap.getContentPane());
        TimKiemKhoaTap.getContentPane().setLayout(TimKiemKhoaTapLayout);
        TimKiemKhoaTapLayout.setHorizontalGroup(
            TimKiemKhoaTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TimKiemKhoaTapLayout.setVerticalGroup(
            TimKiemKhoaTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        KhoaTapDaDangKy.setModal(true);
        KhoaTapDaDangKy.setResizable(false);
        KhoaTapDaDangKy.setSize(new java.awt.Dimension(645, 475));
        KhoaTapDaDangKy.setType(java.awt.Window.Type.UTILITY);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Các khoá tập đã đăng ký");

        pnKT2.setBackground(new java.awt.Color(246, 233, 220));
        pnKT2.setBorder(null);

        pnkt_ktddk.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout pnkt_ktddkLayout = new javax.swing.GroupLayout(pnkt_ktddk);
        pnkt_ktddk.setLayout(pnkt_ktddkLayout);
        pnkt_ktddkLayout.setHorizontalGroup(
            pnkt_ktddkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        pnkt_ktddkLayout.setVerticalGroup(
            pnkt_ktddkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        pnKT2.setViewportView(pnkt_ktddk);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnKT2)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnKT2))
        );

        javax.swing.GroupLayout KhoaTapDaDangKyLayout = new javax.swing.GroupLayout(KhoaTapDaDangKy.getContentPane());
        KhoaTapDaDangKy.getContentPane().setLayout(KhoaTapDaDangKyLayout);
        KhoaTapDaDangKyLayout.setHorizontalGroup(
            KhoaTapDaDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        KhoaTapDaDangKyLayout.setVerticalGroup(
            KhoaTapDaDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LichTap.setModal(true);
        LichTap.setResizable(false);
        LichTap.setSize(new java.awt.Dimension(645, 475));
        LichTap.setType(java.awt.Window.Type.UTILITY);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Các khoá tập đã đăng ký");

        pnKT4.setBackground(new java.awt.Color(246, 233, 220));
        pnKT4.setBorder(null);

        pnkt_lt.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout pnkt_ltLayout = new javax.swing.GroupLayout(pnkt_lt);
        pnkt_lt.setLayout(pnkt_ltLayout);
        pnkt_ltLayout.setHorizontalGroup(
            pnkt_ltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        pnkt_ltLayout.setVerticalGroup(
            pnkt_ltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        pnKT4.setViewportView(pnkt_lt);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnKT4)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnKT4))
        );

        javax.swing.GroupLayout LichTapLayout = new javax.swing.GroupLayout(LichTap.getContentPane());
        LichTap.getContentPane().setLayout(LichTapLayout);
        LichTapLayout.setHorizontalGroup(
            LichTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LichTapLayout.setVerticalGroup(
            LichTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CaNhan.setModal(true);
        CaNhan.setResizable(false);
        CaNhan.setSize(new java.awt.Dimension(645, 475));
        CaNhan.setType(java.awt.Window.Type.UTILITY);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Thông tin cá nhân học viên");

        jPanel20.setBackground(new java.awt.Color(250, 250, 250));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-user-100.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Họ tên:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Mã học viên:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Ngày đăng ký tài khoản");

        txtHoTen_CN.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtHoTen_CN.setForeground(new java.awt.Color(0, 0, 0));
        txtHoTen_CN.setText("abc");

        txtID_CN.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtID_CN.setForeground(new java.awt.Color(0, 0, 0));
        txtID_CN.setText("abc");

        txtNgayDK_CN.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtNgayDK_CN.setForeground(new java.awt.Color(0, 0, 0));
        txtNgayDK_CN.setText("abc");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 153));
        jLabel35.setText("TheDuckGym@gmail.com");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Điện thoại");

        txtDienThoai_CN.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtDienThoai_CN.setForeground(new java.awt.Color(0, 0, 0));
        txtDienThoai_CN.setText("abc");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel24))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen_CN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtID_CN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayDK_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDienThoai_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(txtHoTen_CN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID_CN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(txtDienThoai_CN))
                .addGap(9, 9, 9)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(txtNgayDK_CN, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jLabel35))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(198, 198, 198))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CaNhanLayout = new javax.swing.GroupLayout(CaNhan.getContentPane());
        CaNhan.getContentPane().setLayout(CaNhanLayout);
        CaNhanLayout.setHorizontalGroup(
            CaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CaNhanLayout.setVerticalGroup(
            CaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JOptionPane.setBackground(new java.awt.Color(255, 255, 255));
        JOptionPane.setForeground(new java.awt.Color(51, 51, 51));
        JOptionPane.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setIconImage(new ImageIcon(getClass().getResource("/Material/Icon/Screenshot 2021-12-04 193911.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btQLTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btQLTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btQLTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-search-24.png"))); // NOI18N
        btQLTaiKhoan.setText("Tìm kiếm khoá tập");
        btQLTaiKhoan.setBorderPainted(false);
        btQLTaiKhoan.setContentAreaFilled(false);
        btQLTaiKhoan.setFocusPainted(false);
        btQLTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btQLTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btQLTaiKhoanMouseExited(evt);
            }
        });
        btQLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLTaiKhoanActionPerformed(evt);
            }
        });

        btQLNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btQLNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-syllabus-24.png"))); // NOI18N
        btQLNhanVien.setText("Khoá tập đã đăng ký");
        btQLNhanVien.setBorderPainted(false);
        btQLNhanVien.setContentAreaFilled(false);
        btQLNhanVien.setFocusPainted(false);
        btQLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btQLNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btQLNhanVienMouseExited(evt);
            }
        });
        btQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLNhanVienActionPerformed(evt);
            }
        });

        btQLKhoaTap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btQLKhoaTap.setForeground(new java.awt.Color(255, 255, 255));
        btQLKhoaTap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-schedule-24.png"))); // NOI18N
        btQLKhoaTap.setText("Lịch tập");
        btQLKhoaTap.setBorderPainted(false);
        btQLKhoaTap.setContentAreaFilled(false);
        btQLKhoaTap.setFocusPainted(false);
        btQLKhoaTap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btQLKhoaTapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btQLKhoaTapMouseExited(evt);
            }
        });
        btQLKhoaTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLKhoaTapActionPerformed(evt);
            }
        });

        btCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        btCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        btCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-user-24.png"))); // NOI18N
        btCaNhan.setText("Cá nhân");
        btCaNhan.setBorderPainted(false);
        btCaNhan.setContentAreaFilled(false);
        btCaNhan.setFocusPainted(false);
        btCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCaNhanMouseExited(evt);
            }
        });
        btCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btQLTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(btQLKhoaTap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btQLTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btQLKhoaTap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        ID.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("______________");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("The Duck Gym");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("GET HEALTHY SHAPE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Xin chào, chúc một ngày tốt lành");

        jPanel17.setBackground(new java.awt.Color(91, 91, 91));

        btDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btDoiMatKhau.setText("Đổi mật khẩu");
        btDoiMatKhau.setBorderPainted(false);
        btDoiMatKhau.setContentAreaFilled(false);
        btDoiMatKhau.setFocusPainted(false);
        btDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDoiMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDoiMatKhauMouseExited(evt);
            }
        });
        btDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(91, 91, 91));

        btDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btDangXuat.setText("Đăng xuất");
        btDangXuat.setBorderPainted(false);
        btDangXuat.setContentAreaFilled(false);
        btDangXuat.setFocusPainted(false);
        btDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDangXuatMouseExited(evt);
            }
        });
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        mainFrame.setBackground(new java.awt.Color(255, 255, 255));
        mainFrame.setForeground(new java.awt.Color(102, 102, 102));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Cập nhật");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel6.setBackground(new java.awt.Color(220, 220, 225));
        jPanel6.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Số lượng khoá tập đã đăng ký:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Số lượng khoá tập đang thực hiện:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Số lượng khoá tập đã huỷ:");

        txtslKhoaTapDaDangKy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtslKhoaTapDaDangKy.setForeground(new java.awt.Color(51, 51, 51));
        txtslKhoaTapDaDangKy.setText("0");

        txtslKhoaTapDangThucHien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtslKhoaTapDangThucHien.setForeground(new java.awt.Color(51, 51, 51));
        txtslKhoaTapDangThucHien.setText("0");

        txtslKhoaTapDaHuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtslKhoaTapDaHuy.setForeground(new java.awt.Color(51, 51, 51));
        txtslKhoaTapDaHuy.setText("0");

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-call-statistics-20.png"))); // NOI18N
        jLabel1.setText("Thống kê nhanh");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtslKhoaTapDangThucHien, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txtslKhoaTapDaDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtslKhoaTapDaHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtslKhoaTapDaDangKy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtslKhoaTapDangThucHien)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtslKhoaTapDaHuy))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Trang Chủ");

        jPanel7.setBackground(new java.awt.Color(220, 220, 225));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-pulse-20.png"))); // NOI18N
        jLabel17.setText("Tính chỉ số BMI");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Chiều cao");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Cân nặng");

        txtChieuCao.setBackground(new java.awt.Color(220, 220, 225));
        txtChieuCao.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtChieuCao.setForeground(new java.awt.Color(51, 51, 51));
        txtChieuCao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtChieuCao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChieuCaoKeyReleased(evt);
            }
        });

        txtCanNang.setBackground(new java.awt.Color(220, 220, 225));
        txtCanNang.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtCanNang.setForeground(new java.awt.Color(51, 51, 51));
        txtCanNang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCanNang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCanNangKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Kết quả:");

        txtNhanXet.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNhanXet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChieuCao, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtCanNang)
                            .addComponent(txtKetQua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtChieuCao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNhanXet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/Untitled-1.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Chăm chỉ");

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rèn luyện");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("để tạo cho bản thân một cái thói quen tốt.");

        jLabel14.setText("________________________________________________");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("để giúp cơ thể luôn khoẻ mạnh.");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel16.setText("TheDuckGym");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(220, 220, 225));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Material/Icon/icons8-heart-with-pulse-20.png"))); // NOI18N
        jLabel23.setText("Mỗi ngày 1 lời khuyên");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtLoiKhuyen.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        txtLoiKhuyen.setForeground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtLoiKhuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLoiKhuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btQLNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLNhanVienMouseEntered
        btQLNhanVien.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_btQLNhanVienMouseEntered

    private void btQLKhoaTapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLKhoaTapMouseEntered
        btQLKhoaTap.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_btQLKhoaTapMouseEntered

    private void btQLTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLTaiKhoanMouseEntered
        btQLTaiKhoan.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_btQLTaiKhoanMouseEntered

    private void btQLTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLTaiKhoanMouseExited
        btQLTaiKhoan.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btQLTaiKhoanMouseExited

    private void btQLNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLNhanVienMouseExited
        btQLNhanVien.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btQLNhanVienMouseExited

    private void btQLKhoaTapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLKhoaTapMouseExited
        btQLKhoaTap.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btQLKhoaTapMouseExited

    private void btQLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLTaiKhoanActionPerformed
        TimKiemKhoaTap.setLocationRelativeTo(mainFrame);
        deleteDuLieu();
        TimKiemKhoaTap();
        TimKiemKhoaTap.setVisible(true);
    }//GEN-LAST:event_btQLTaiKhoanActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ThongKeNhanh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btDoiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDoiMatKhauMouseEntered
        btDoiMatKhau.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_btDoiMatKhauMouseEntered

    private void btDoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDoiMatKhauMouseExited
        btDoiMatKhau.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btDoiMatKhauMouseExited

    private void btDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseEntered
        btDangXuat.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_btDangXuatMouseEntered

    private void btDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseExited
        btDangXuat.setForeground(new Color(255,255,255));;
    }//GEN-LAST:event_btDangXuatMouseExited

    private void txtChieuCaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChieuCaoKeyReleased
        BMI();
    }//GEN-LAST:event_txtChieuCaoKeyReleased

    private void txtCanNangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCanNangKeyPressed
        BMI();
    }//GEN-LAST:event_txtCanNangKeyPressed

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        Login log = new Login();
        dispose();
        log.setVisible(true);
    }//GEN-LAST:event_btDangXuatActionPerformed

    private void btDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoiMatKhauActionPerformed
        DoiMatKhau.setLocationRelativeTo(mainFrame);
        DoiMatKhau.setVisible(true);
    }//GEN-LAST:event_btDoiMatKhauActionPerformed

    private void btQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLNhanVienActionPerformed
        KhoaTapDaDangKy.setLocationRelativeTo(mainFrame);
        deleteDuLieu();
        KhoaTapDaDangKy();
        KhoaTapDaDangKy.setVisible(true);
    }//GEN-LAST:event_btQLNhanVienActionPerformed

    private void btQLKhoaTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLKhoaTapActionPerformed
        LichTap.setLocationRelativeTo(mainFrame);
        deleteDuLieu();
        LichTap();
        LichTap.setVisible(true);
    }//GEN-LAST:event_btQLKhoaTapActionPerformed

    private void btCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCaNhanMouseEntered
        btCaNhan.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_btCaNhanMouseEntered

    private void btCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCaNhanMouseExited
        btCaNhan.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btCaNhanMouseExited

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        if(checkDoiMatKhau()==true){
            ThayDoiMatKhau();
        }else{
            JOptionPane.showMessageDialog(this,"Xin vui lòng không để lại ô trống");
        }
        
    }//GEN-LAST:event_btXacNhanActionPerformed

    private void btCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaNhanActionPerformed
        CaNhan.setLocationRelativeTo(mainFrame);
        setDuLieu_CN();
        CaNhan.setVisible(true);
    }//GEN-LAST:event_btCaNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuHocVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CaNhan;
    private javax.swing.JDialog DoiMatKhau;
    private javax.swing.JLabel ID;
    private javax.swing.JOptionPane JOptionPane;
    private javax.swing.JDialog KhoaTapDaDangKy;
    private javax.swing.JDialog LichTap;
    private javax.swing.JDialog TimKiemKhoaTap;
    private javax.swing.JButton btCaNhan;
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btDoiMatKhau;
    private javax.swing.JButton btQLKhoaTap;
    private javax.swing.JButton btQLNhanVien;
    private javax.swing.JButton btQLTaiKhoan;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JScrollPane pnKT1;
    private javax.swing.JScrollPane pnKT2;
    private javax.swing.JScrollPane pnKT4;
    private javax.swing.JPanel pnkt_ktddk;
    private javax.swing.JPanel pnkt_lt;
    private javax.swing.JPanel pnkt_tkkt;
    private javax.swing.JTextField txtCanNang;
    private javax.swing.JTextField txtChieuCao;
    private javax.swing.JLabel txtDienThoai_CN;
    private javax.swing.JLabel txtHoTen_CN;
    private javax.swing.JLabel txtID_CN;
    private javax.swing.JLabel txtKetQua;
    private javax.swing.JLabel txtLoiKhuyen;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JLabel txtNgayDK_CN;
    private javax.swing.JLabel txtNhanXet;
    private javax.swing.JPasswordField txtXacNhan;
    private javax.swing.JLabel txtslKhoaTapDaDangKy;
    private javax.swing.JLabel txtslKhoaTapDaHuy;
    private javax.swing.JLabel txtslKhoaTapDangThucHien;
    // End of variables declaration//GEN-END:variables
    //------------------------------------------------------------Trang Chu--------------------------------------------------------------
    public void setUser(String a){
        user = a;
        ID.setText(user);
    }
    public void ThongKeNhanh(){
        ArrayList<DSDK> listdsdk;
        ArrayList<LichTap> listlt;
        try{
            listdsdk = DSDKDao.Select();
            listlt = LichTapDao.Select();
            txtslKhoaTapDaDangKy.setText(String.valueOf(slKhoaTapDaDangKy(listdsdk)));
            txtslKhoaTapDangThucHien.setText(String.valueOf(slKhoaTapDangThucHien(listdsdk)));
            txtslKhoaTapDaHuy.setText(String.valueOf(slKhoaTapDaHuy(listdsdk)));
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public String slKhoaTapDaDangKy(ArrayList<DSDK> list){
        int count = 0;
        for(int i = 0;i < list.size();i++){
            if(list.get(i).getIDHV().equals(ID)){
                count++;
            }
        }
        return String.valueOf(count);
    }
    public String slKhoaTapDangThucHien(ArrayList<DSDK> list){
        int count = 0;
        for(int i = 0;i < list.size();i++){
            if(list.get(i).getIDHV().equals(ID) && list.get(i).getTinhTrangKT().equals("Đang thực hiện")){
                count++;
            }
        }
        return String.valueOf(count);
    }
    public String slKhoaTapDaHuy(ArrayList<DSDK> list){
        int count = 0;
        for(int i = 0;i < list.size();i++){
            if(list.get(i).getIDHV().equals(ID) && list.get(i).getTinhTrangKT().equals("Đã huỷ")){
                count++;
            }
        }
        return String.valueOf(count);
    }
    public void LoiKhuyen(){
        Random r = new Random();
        int number = r.nextInt(3)+1;
        if(number == 1){
            txtLoiKhuyen.setText("- Thử cân bằng lượng rau và\n protein nhỉ?");
        }else if(number  == 2){
            txtLoiKhuyen.setText("- Chạy bộ\n sáng sớm cũng rất khoẻ");
        }else{
            txtLoiKhuyen.setText("- Vóc dáng bự, sáu múi thì\n gái theo nhiều lắm :3 ");
        }
    }
    public void BMI(){
        if(!(txtChieuCao.getText().equals("") || txtCanNang.getText().equals(""))){
            try{
                float bmi = 0;
                float chieucao = Float.parseFloat(txtChieuCao.getText());
                float cannang = Float.parseFloat(txtCanNang.getText());
                bmi = (chieucao*chieucao);
                bmi = cannang/bmi;
                bmi = bmi*100000;
                txtKetQua.setText(String.valueOf(bmi));
                if(bmi<18){
                    txtNhanXet.setText("- Thiếu cân");
                    txtNhanXet.setForeground(new Color(102,102,255));
                }else if(bmi>18 && bmi<25){
                    txtNhanXet.setText("- Bình thường");
                    txtNhanXet.setForeground(new Color(51,204,0));
                }else if(bmi>25 && bmi<29){
                    txtNhanXet.setText("- Thừa cân");
                    txtNhanXet.setForeground(new Color(102,102,255));
                }else{
                    txtNhanXet.setText("- Béo phì");
                    txtNhanXet.setForeground(new Color(255,51,51));
                }
            }catch(Exception ex){
                
            }
        }else{
            txtKetQua.setText("");
            txtNhanXet.setText("");
            txtNhanXet.setForeground(new Color(187,187,187));
        }
    }
    public void ThayDoiMatKhau(){
        if(txtMatKhauMoi.getText().equals(txtXacNhan.getText())){
            int result = DoiMatKhauHelper.DoiMatKhau(user,txtMatKhauMoi.getText());
            if(result > 0){
                JOptionPane.showMessageDialog(this, "Mật khẩu đổi thành công");
            }else{
                JOptionPane.showMessageDialog(this, "Mật khẩu thay đổi thất bại");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không đúng");
        }
    }
    public boolean checkDoiMatKhau(){
        if(txtMatKhauMoi.getText().equals("") || txtXacNhan.getText().equals("")){
            return false;
        }else{
            return true;
        }
    }
    public void TimKiemKhoaTap(){
        ArrayList<KhoaTap> list = new ArrayList<KhoaTap>();
        try{
            list = KhoaTapDao.Select();
            if(list.size() != 0){
                TaoDoiTuong_TimKiemKhoaTap(list);
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void deleteDuLieu(){
        pnkt_tkkt.removeAll();
        pnkt_ktddk.removeAll();
        pnkt_lt.removeAll();
    }
    
    public void TaoDoiTuong_TimKiemKhoaTap(ArrayList<KhoaTap> list){
        int sl = list.size();
        pnkt_tkkt.setPreferredSize(new Dimension(600, (100*sl)+100));
        pnkt_tkkt.setLayout(new FlowLayout(1,0,20));
        JPanel[] pn_tkkt = new JPanel[sl];
        JPanel[] pnlb_tkkt = new JPanel[sl];
        JLabel[] tenkt_tkkt = new JLabel[sl];
        JLabel[] pic_tkkt = new JLabel[sl];
        JLabel[] tenHLV_tkkt = new JLabel[sl];
        JLabel[] bt_tkkt = new JLabel[sl];
        JLabel[] gia_tkkt = new JLabel[sl];
        JButton[] but_tkkt = new JButton[sl];
        int i;
        for(i = 0;i < sl;i++){
            final int index = i;
            pn_tkkt[i] = new JPanel();
            pn_tkkt[i].setLayout(null);
            pnlb_tkkt[i] = new JPanel();
            pnlb_tkkt[i].setLayout(null);
            tenkt_tkkt[i] = new JLabel("Tên khoá tập: "+list.get(i).getTenKT());
            pnlb_tkkt[i].add(tenkt_tkkt[i]);
            pic_tkkt[i] = new JLabel();
            tenHLV_tkkt[i] = new JLabel("Tên HLV: "+list.get(i).getTenHLV());
            bt_tkkt[i] = new JLabel("Số buổi tập: "+list.get(i).getSoBuoiTap());
            gia_tkkt[i] = new JLabel("Giá: "+list.get(i).getGia());
            but_tkkt[i] = new JButton("Đăng ký");
            tenHLV_tkkt[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            gia_tkkt[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            bt_tkkt[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            pn_tkkt[i].setBackground(new Color(220,220,225));
            pn_tkkt[i].setPreferredSize(new Dimension(600,100));
            pnkt_tkkt.add(pn_tkkt[i]);
            pn_tkkt[i].add(pnlb_tkkt[i]);
            pn_tkkt[i].add(pic_tkkt[i]);
            pn_tkkt[i].add(tenHLV_tkkt[i]);
            pn_tkkt[i].add(bt_tkkt[i]);
            pn_tkkt[i].add(but_tkkt[i]);
            pn_tkkt[i].add(gia_tkkt[i]);
            pnlb_tkkt[i].setBounds(0,-5,632,30);
            pnlb_tkkt[i].setBackground(new Color(51,51,51));
            tenkt_tkkt[i].setBounds(10,0,200,30);
            tenkt_tkkt[i].setForeground(new Color(255,255,255));
            tenkt_tkkt[i].setFont(new Font("Segoe UI",Font.ITALIC + Font.BOLD,14));
            pic_tkkt[i].setBounds(10,30,300,60);
            pic_tkkt[i].setBorder(new MatteBorder(1,1,1,1,new Color(0,0,0)));
            pic_tkkt[i].setIcon(new ImageIcon(getClass().getResource("/Material/bannerkt.png")));
            tenHLV_tkkt[i].setBounds(320,30,170,20);
            gia_tkkt[i].setBounds(320,50,170,20);
            bt_tkkt[i].setBounds(320,70,170,20);
            but_tkkt[i].setBounds(500,60,90,30);
            but_tkkt[i].setFocusPainted(false);
            but_tkkt[i].setBorderPainted(false);
            but_tkkt[i].setBorder(new EmptyBorder(1,1,1,1));
            but_tkkt[i].setBackground(new Color(204,204,204));
            but_tkkt[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            but_tkkt[i].setForeground(new Color(51,51,51));
            but_tkkt[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e){
                    chonKT(index);
                }
            });
        }
    }
    public void chonKT(int i){
        int yn = JOptionPane.showConfirmDialog(null,"Xác nhận đăng ký? Hệ thống sẽ tự động trừ tiền trong ví!!","Xác nhận",JOptionPane.YES_NO_OPTION);
        if(yn == JOptionPane.YES_OPTION){
            try{
                ArrayList<KhoaTap> list = KhoaTapDao.Select();
                String MaKT = list.get(i).getMaKT();
                DSDK model = new DSDK(0,user,MaKT,"",0,"",0,"","");
                int s = DSDKDao.dangKy(model);
                if(s > 0){
                    JOptionPane.showMessageDialog(this, "Thành công!! Xin chờ đợi qtv phê duyệt và xếp lịch");
                }else{
                    throw new Exception();
                }
             }catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Thất bại!!");
             }           
       }
    }
    public void KhoaTapDaDangKy(){
        ArrayList<DSDK> listTemp = new ArrayList<DSDK>();
        ArrayList<DSDK> list = new ArrayList<DSDK>();
        ArrayList<KhoaTap> listkt = new ArrayList<KhoaTap>();
        try{
            listkt = KhoaTapDao.Select();
            listTemp = DSDKDao.Select();
            for(int i = 0;i < listTemp.size();i++){
                if(listTemp.get(i).getIDHV().equals(user)){
                    list.add(listTemp.get(i));
                }
            }
            if(list.size() != 0 ){
                TaoDoiTuong_KhoaTapDaDangKy(list, listkt);
            }      
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void TaoDoiTuong_KhoaTapDaDangKy(ArrayList<DSDK> list,ArrayList<KhoaTap> listkt){
        int sl = list.size();
        pnkt_ktddk.setPreferredSize(new Dimension(600, (100*sl)+100));
        pnkt_ktddk.setLayout(new FlowLayout(1,0,20));
        JPanel[] pn_ktddk = new JPanel[sl];
        JPanel[] pnlb_ktddk = new JPanel[sl];
        JLabel[] tenkt_ktddk = new JLabel[sl];
        JLabel[] pic_ktddk = new JLabel[sl];
        JLabel[] tenHLV_ktddk = new JLabel[sl];
        JLabel[] bt_ktddk = new JLabel[sl];
        JLabel[] tinhTrang_ktddk = new JLabel[sl];
        JButton[] but_ktddk = new JButton[sl];
        for(int i = 0;i < sl;i++){
            final int index = i;
            String KT = "";
            String HLV = "";
            for(int j = 0;j < listkt.size();j++){
                if(listkt.get(j).getMaKT().equals(list.get(i).getMaKT())){
                    KT = listkt.get(j).getTenKT();
                    HLV = listkt.get(j).getTenHLV();
                    break;
                }
            }
            pn_ktddk[i] = new JPanel();
            pn_ktddk[i].setLayout(null);
            pnlb_ktddk[i] = new JPanel();
            pnlb_ktddk[i].setLayout(null);
            tenkt_ktddk[i] = new JLabel("Tên khoá tập: "+KT+"("+list.get(i).getMaKT()+")");
            pnlb_ktddk[i].add(tenkt_ktddk[i]);
            pic_ktddk[i] = new JLabel();
            tenHLV_ktddk[i] = new JLabel("Tên HLV: "+HLV);
            bt_ktddk[i] = new JLabel("Số buổi tập: "+list.get(i).getSoBuoiTap());
            tinhTrang_ktddk[i] = new JLabel("Tình trạng: "+list.get(i).getTinhTrangKT());
            but_ktddk[i] = new JButton("Huỷ khoá học");
            tenHLV_ktddk[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            tinhTrang_ktddk[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            bt_ktddk[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            pn_ktddk[i].setBackground(new Color(220,220,225));
            pn_ktddk[i].setPreferredSize(new Dimension(600,100));
            pnkt_ktddk.add(pn_ktddk[i]);
            pn_ktddk[i].add(pnlb_ktddk[i]);
            pn_ktddk[i].add(pic_ktddk[i]);
            pn_ktddk[i].add(tenHLV_ktddk[i]);
            pn_ktddk[i].add(bt_ktddk[i]);
            pn_ktddk[i].add(but_ktddk[i]);
            pn_ktddk[i].add(tinhTrang_ktddk[i]);
            pnlb_ktddk[i].setBounds(0,-5,632,30);
            pnlb_ktddk[i].setBackground(new Color(51,51,51));
            tenkt_ktddk[i].setBounds(10,0,400,30);
            tenkt_ktddk[i].setForeground(new Color(255,255,255));
            tenkt_ktddk[i].setFont(new Font("Segoe UI",Font.ITALIC + Font.BOLD,14));
            pic_ktddk[i].setBounds(10,30,300,60);
            pic_ktddk[i].setBorder(new MatteBorder(1,1,1,1,new Color(0,0,0)));
            pic_ktddk[i].setIcon(new ImageIcon(getClass().getResource("/Material/bannerkt.png")));
            tenHLV_ktddk[i].setBounds(320,30,170,20);
            tinhTrang_ktddk[i].setBounds(320,50,170,20);
            if(tinhTrang_ktddk[i].getText().equals("Tình trạng: Chưa xếp lịch")){
                tinhTrang_ktddk[i].setForeground(new Color(0,204,51));
            }else if(tinhTrang_ktddk[i].getText().equals("Tình trạng: Đang thực hiện")){
                tinhTrang_ktddk[i].setForeground(new Color(51,0,204));
            }else{
                tinhTrang_ktddk[i].setForeground(new Color(255,0,0));
                but_ktddk[i].setEnabled(false);
            }
            bt_ktddk[i].setBounds(320,70,170,20);
            but_ktddk[i].setBounds(500,60,90,30);
            but_ktddk[i].setFocusPainted(false);
            but_ktddk[i].setBorderPainted(false);
            but_ktddk[i].setBorder(new EmptyBorder(1,1,1,1));
            but_ktddk[i].setBackground(new Color(204,204,204));
            but_ktddk[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            but_ktddk[i].setForeground(new Color(51,51,51));
            but_ktddk[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e){
                    huyKT(index);
                }
            });
        }
    }
    public void huyKT(int index){
        int yn = JOptionPane.showConfirmDialog(null,"Xác nhận huỷ?","Xác nhận",JOptionPane.YES_NO_OPTION);
        if(yn == JOptionPane.YES_OPTION){
            ArrayList<DSDK> listTemp = new ArrayList<DSDK>();
            ArrayList<DSDK> list = new ArrayList<DSDK>();
            ArrayList<KhoaTap> listkt = new ArrayList<KhoaTap>();
            try{
                listkt = KhoaTapDao.Select();
                listTemp = DSDKDao.Select();
                for(int i = 0;i < listTemp.size();i++){
                    if(listTemp.get(i).getIDHV().equals(user)){
                        list.add(listTemp.get(i));
                    }
                }
                int MaDK = list.get(index).getMaDK();
                String TinhTrang = "Đã huỷ";
                DSDK model = new DSDK(MaDK,"","","",0,"",0,TinhTrang,"");
                int s = DSDKDao.update(model);
                if(s > 0){
                    JOptionPane.showMessageDialog(this, "Huỷ thành công");
                    deleteDuLieu();
                    KhoaTapDaDangKy();
                }else{
                    throw new Exception();
                }
            }catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Huỷ thất bại");
            }
        }
    }
    public void LichTap(){
        ArrayList<LichTap> list = new ArrayList<LichTap>();
        ArrayList<LichTap> listTemp = new ArrayList<LichTap>();
        try{
            listTemp = LichTapDao.Select();
            for(int i = 0;i<listTemp.size();i++){
                if(listTemp.get(i).getIDHV().equals(user) ){
                    SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                    LocalDate d = LocalDate.now();
                    Date d1 = f.parse(String.valueOf(d));
                    Date d2 = f.parse(String.valueOf(listTemp.get(i).getNgayTap()));
                    if(d1.compareTo(d2) <= 0){
                        list.add(listTemp.get(i));
                    }
                }
            }
            if(list.size() != 0){
                TaoDoiTuong_LichTap(list);
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void TaoDoiTuong_LichTap(ArrayList<LichTap> list){
        int sl = list.size();
        pnkt_lt.setPreferredSize(new Dimension(600, (100*(sl/3))+500));
        pnkt_lt.setLayout(new FlowLayout(1,20,20));
        JPanel[] pn_lt = new JPanel[sl];
        JPanel[] pnlb_lt = new JPanel[sl];
        JLabel[] ngay_lt = new JLabel[sl];
        JLabel[] tenkt_lt = new JLabel[sl];
        JLabel[] ghichu_lt = new JLabel[sl];
        for(int i = 0;i < sl;i++){
            pn_lt[i] = new JPanel(null);
            pnlb_lt[i] = new JPanel(null);
            ngay_lt[i] = new JLabel("Ngày: "+list.get(i).getNgayTap());
            ngay_lt[i].setFont(new Font("Segoe UI",Font.ITALIC + Font.BOLD,14));
            tenkt_lt[i] = new JLabel("Mã KT: "+list.get(i).getMaKT());
            tenkt_lt[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            ghichu_lt[i] = new JLabel("Ghi chú: "+list.get(i).getGhiChu());
            ghichu_lt[i].setFont(new Font("Segoe UI",Font.BOLD,12));
            pnlb_lt[i].add(ngay_lt[i]);
            pn_lt[i].add(pnlb_lt[i]);
            pn_lt[i].add(tenkt_lt[i]);
            pn_lt[i].add(ghichu_lt[i]);
            pn_lt[i].setBackground(new Color(220,220,225));
            pn_lt[i].setPreferredSize(new Dimension(175,100));
            pnlb_lt[i].setBounds(0,-5,175,30);
            ngay_lt[i].setBounds(0,0,175,30);
            ngay_lt[i].setHorizontalAlignment(SwingConstants.CENTER);
            ngay_lt[i].setForeground(new Color(255,255,255));
            pnlb_lt[i].setBackground(new Color(51,51,51));
            tenkt_lt[i].setForeground(new Color(51,51,51));
            tenkt_lt[i].setBounds(5,30,100,20);
            ghichu_lt[i].setBounds(5,50,150,20);
            pnkt_lt.add(pn_lt[i]);
        }
    }
    public void setDuLieu_CN(){
        try{
            ArrayList<TaiKhoan> list1 = TaiKhoanDao.Select();
            ArrayList<HocVien> list2 = HocVienDao.Select();
            txtID_CN.setText(user);
            for(TaiKhoan i: list1){
                if(i.getID().equals(user)){
                    txtNgayDK_CN.setText(i.getNgayDK());
                }
            }
            for(HocVien i: list2){
                if(i.getIDHV().equals(user)){
                    txtHoTen_CN.setText(i.getHoTen());
                    txtDienThoai_CN.setText(i.getDienThoai());
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
}
